name: sync_lyrics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-157.0.dev <4.0.0'

dependencies:
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  path_provider: ^2.1.3
  process_run: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
